services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
    env_file:
      - ./vpn.env
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_WEB_UI=flood-for-transmission
    volumes:
      - /mnt/jellydrive/downloads:/data # Transmission expects /data
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/jellydrive/radarr:/config
      - /mnt/jellydrive/movies:/movies
      - /mnt/jellydrive/downloads/completed:/downloads # maps to /data/completed in Transmission

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/jellydrive/sonarr:/config
      - /mnt/jellydrive/tv:/tv
      - /mnt/jellydrive/anime:/anime
      - /mnt/jellydrive/downloads/completed:/downloads

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: always
    ports:
      - "8686:8686"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/jellydrive/lidarr:/config
      - /mnt/jellydrive/music:/music
      - /mnt/jellydrive/downloads/completed:/downloads

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/jellydrive/prowlarr:/config
      - /mnt/jellydrive/downloads/watch:/downloads

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=America/Chicago
    volumes:
      - /mnt/jellydrive/heimdall:/config

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: always
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=America/Chicago
